# This is a basic workflow to help you get started with Actions

name: Copy File

on:
  push:
    branches:
      - main  

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Copy File
      run: cp ./copy.yml ./test/copy.yml

